// frontend/src/components/Footer.jsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { Separator } from '@/components/ui/separator.jsx'
import { getCompanyInfo, getMapboxPublicKey } from '@/lib/api.ts'

function loadScriptOnce(src, id) {
  return new Promise((resolve, reject) => {
    if (id && document.getElementById(id)) return resolve()
    const s = document.createElement('script')
    if (id) s.id = id
    s.src = src
    s.async = true
    s.onload = () => resolve()
    s.onerror = () => reject(new Error('Falha ao carregar script: ' + src))
    document.head.appendChild(s)
  })
}

function loadCssOnce(href, id) {
  return new Promise((resolve, reject) => {
    if (id && document.getElementById(id)) return resolve()
    const l = document.createElement('link')
    if (id) l.id = id
    l.rel = 'stylesheet'
    l.href = href
    l.onload = () => resolve()
    l.onerror = () => reject(new Error('Falha ao carregar CSS: ' + href))
    document.head.appendChild(l)
  })
}

function getReadableTextColor(hex) {
  const c = (hex || '').toString()
  const m = c.match(/^#?([0-9a-f]{6})$/i)
  const base = m ? m[1] : '111827' // slate-900
  const r = parseInt(base.substr(0, 2), 16)
  const g = parseInt(base.substr(2, 2), 16)
  const b = parseInt(base.substr(4, 2), 16)
  const yiq = (r * 299 + g * 587 + b * 114) / 1000
  return yiq >= 128 ? '#111827' : '#FFFFFF'
}

// Helpers adicionais: normalizar URL de imagem e construir link do WhatsApp
function normalizeImageUrl(url) {
  if (!url) return ''
  try {
    // Mantém URLs absolutas (http/https/data)
    if (/^(https?:)?\/\//i.test(url) || url.startsWith('data:')) return url
    // Caso seja relativo, tenta resolver contra a origem atual
    return new URL(url, window.location.origin).toString()
  } catch (_) {
    return url
  }
}

function onlyDigits(str) {
  return (str || '').replace(/\D+/g, '')
}

function buildWhatsAppLink(phone) {
  const digits = onlyDigits(phone)
  // Se já começar com 55 (Brasil) e tiver 12-13+ dígitos, mantém; caso contrário, prefixa 55
  const normalized = digits.startsWith('55') ? digits : `55${digits}`
  return `https://wa.me/${normalized}`
}

export default function Footer() {
  const [company, setCompany] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [mapboxKey, setMapboxKey] = useState(null)
  const mapRef = useRef(null)
  const mapInited = useRef(false)

  useEffect(() => {
    let mounted = true
    ;(async () => {
      try {
        setLoading(true)
        const [info, key] = await Promise.all([
          getCompanyInfo().catch(() => null),
          getMapboxPublicKey().catch(() => null),
        ])
        if (!mounted) return
        setCompany(info)
        setMapboxKey(key)
      } catch (e) {
        if (!mounted) return
        setError(e?.message || 'Falha ao carregar informações da empresa')
      } finally {
        if (mounted) setLoading(false)
      }
    })()
    return () => { mounted = false }
  }, [])

  const bgColor = company?.company_color || '#111827'
  const textColor = useMemo(() => getReadableTextColor(bgColor), [bgColor])

  useEffect(() => {
    if (mapInited.current) return
    if (!mapboxKey) return
    if (!company?.latitude || !company?.longitude) return
    if (!mapRef.current) return

    let cancelled = false

    ;(async () => {
      try {
        await loadCssOnce('https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css', 'mapbox-gl-css')
        await loadScriptOnce('https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js', 'mapbox-gl-js')
        if (cancelled) return
        if (!window.mapboxgl) throw new Error('Mapbox GL não disponível')
        window.mapboxgl.accessToken = mapboxKey
        const center = [Number(company.longitude), Number(company.latitude)]
        const map = new window.mapboxgl.Map({
          container: mapRef.current,
          style: 'mapbox://styles/mapbox/streets-v11',
          center,
          zoom: 14,
          cooperativeGestures: true,
        })
        new window.mapboxgl.Marker().setLngLat(center).addTo(map)
        mapInited.current = true
      } catch (e) {
        // Silenciar erro no footer; apenas não mostrar o mapa
        // console.error(e)
      }
    })()

    return () => { cancelled = true }
  }, [mapboxKey, company])

  if (loading) return null
  if (!company) return null

  return (
    <footer
      className="mt-8"
      style={{ backgroundColor: bgColor, color: textColor }}
    >
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-start">
          <div className="md:col-span-2 space-y-2">
            {/* Logo + Nome */}
            <div className="flex items-center gap-3">
              {company.logo_url && (
                <img
                  src={normalizeImageUrl(company.logo_url)}
                  alt={company.company_name ? `${company.company_name} logo` : 'Logo'}
                  className="h-10 w-auto object-contain drop-shadow"
                  loading="lazy"
                />
              )}
              <div>
                <div className="text-xl font-semibold">{company.company_name || 'Nossa Empresa'}</div>
                {company.cnpj && (
                  <div className="text-sm opacity-90">CNPJ: {company.cnpj}</div>
                )}
              </div>
            </div>

            {/* Endereço */}
            {company.address && (
              <div className="text-sm opacity-90">{company.address}</div>
            )}
            {company.zip_code && (
              <div className="text-sm opacity-90">CEP: {company.zip_code}</div>
            )}

            {/* WhatsApp */}
            {company.phone && (
              <div className="text-sm opacity-90">
                <a
                  href={buildWhatsAppLink(company.phone)}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline"
                  style={{ color: textColor }}
                >
                  WhatsApp: {company.phone}
                </a>
              </div>
            )}
          </div>

          {/* Mapa ou link para Google Maps */}
          <div>
            {mapboxKey && company?.latitude && company?.longitude ? (
              <div
                ref={mapRef}
                className="h-40 w-full rounded-md overflow-hidden border border-white/10"
                style={{ background: 'rgba(255,255,255,0.05)' }}
              />
            ) : (
              <div className="text-sm opacity-80">
                {company.latitude && company.longitude ? (
                  <a
                    className="underline"
                    style={{ color: textColor }}
                    target="_blank"
                    href={`https://www.google.com/maps?q=${encodeURIComponent(company.latitude + ',' + company.longitude)}`}
                    rel="noreferrer"
                  >
                    Ver no mapa
                  </a>
                ) : (
                  <span>Localização não disponível</span>
                )}
              </div>
            )}
          </div>
        </div>

        <Separator className="my-6 opacity-20" />

        <div className="text-xs opacity-80 flex flex-col sm:flex-row justify-between gap-2">
          <div>
            © {new Date().getFullYear()} {company.company_name || 'Empresa'}. Todos os direitos reservados.
          </div>
          <div>
            Feito com ❤
          </div>
        </div>
      </div>
    </footer>
  )
}

// frontend/src/components/Footer.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { Separator } from '@/components/ui/separator'
import { getCompanyInfo, getMapboxPublicKey } from '@/lib/api'
import { normalizeImageUrl } from '@/lib/utils'

const company = ref<any>(null)
const mapboxKey = ref<string | null>(null)
const mapEl = ref<HTMLElement | null>(null)

const brand = computed(() => company.value?.company_color || '')
function isValidHex(hex: string) {
  return /^#([0-9a-fA-F]{6})$/.test(hex)
}
function pickTextColor(hex: string) {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  const yiq = (r * 299 + g * 587 + b * 114) / 1000
  return yiq >= 128 ? '#111827' : '#ffffff'
}
const bgStyle = computed(() => {
  const c = brand.value
  if (isValidHex(c)) {
    return { backgroundColor: c, color: pickTextColor(c) }
  }
  return {}
})

function buildMapsLink(lat: number, lng: number) {
  return `https://www.google.com/maps?q=${lat},${lng}`
}

async function loadMapboxGL() {
  if ((window as any).mapboxgl) return (window as any).mapboxgl
  await new Promise<void>((resolve, reject) => {
    if (!document.querySelector('link[data-mapbox-gl]')) {
      const link = document.createElement('link')
      link.rel = 'stylesheet'
      link.href = 'https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.css'
      link.setAttribute('data-mapbox-gl', '1')
      document.head.appendChild(link)
    }
    const script = document.createElement('script')
    script.src = 'https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.js'
    script.async = true
    script.onload = () => resolve()
    script.onerror = () => reject(new Error('Falha ao carregar Mapbox GL'))
    document.head.appendChild(script)
  })
  return (window as any).mapboxgl
}

async function initMap() {
  if (!mapEl.value || !company.value?.latitude || !company.value?.longitude || !mapboxKey.value) return
  try {
    const mapboxgl = await loadMapboxGL()
    mapboxgl.accessToken = mapboxKey.value
    const map = new mapboxgl.Map({
      container: mapEl.value,
      style: 'mapbox://styles/mapbox/streets-v12',
      center: [Number(company.value.longitude), Number(company.value.latitude)],
      zoom: 14,
      attributionControl: false,
    })
    new mapboxgl.Marker().setLngLat([Number(company.value.longitude), Number(company.value.latitude)]).addTo(map)
  } catch (e) {
    // silencioso
  }
}

onMounted(async () => {
  try {
    const [info, key] = await Promise.all([getCompanyInfo(), getMapboxPublicKey()])
    company.value = info
    mapboxKey.value = key
    setTimeout(initMap, 0)
  } catch {}
})
</script>

<template>
  <Separator class="my-0" />
  <footer :style="bgStyle" class="w-full">
    <div class="mx-auto max-w-5xl px-4 py-6 grid gap-6 md:grid-cols-3">
      <div class="flex items-center gap-3">
        <img v-if="company?.logo_url" :src="normalizeImageUrl(company?.logo_url)" alt="Logo" class="h-10 w-auto rounded bg-white/90 p-1" />
        <div>
          <h2 class="text-base font-semibold">{{ company?.company_name ?? 'Minha Empresa' }}</h2>
          <p v-if="company?.cnpj" class="text-sm opacity-90">CNPJ: {{ company?.cnpj }}</p>
        </div>
      </div>
      <div class="text-sm space-y-1">
        <p v-if="company?.address">
          {{ company.address }}
          <span v-if="company?.zip_code">- {{ company.zip_code }}</span>
        </p>
        <p v-if="company?.phone">
          <a :href="`tel:${company.phone}`" class="underline underline-offset-2">Telefone: {{ company.phone }}</a>
        </p>
        <p v-if="company?.latitude && company?.longitude">
          <a :href="buildMapsLink(company.latitude, company.longitude)" target="_blank" rel="noopener" class="underline underline-offset-2">Abrir no mapa</a>
        </p>
      </div>
      <div>
        <div v-if="mapboxKey && company?.latitude && company?.longitude" ref="mapEl" class="h-40 w-full rounded-md overflow-hidden ring-1 ring-black/10"></div>
        <div v-else class="text-sm opacity-90">
          <p>Mapa indisponível.</p>
        </div>
      </div>
    </div>
  </footer>
</template>

<style scoped>
</style>
